/**
 * Soundscape files (.tds): custom soundscapes exported and imported, the
 * way layouts are as .tdl (see presetFile.ts for the shared line format).
 * Each line is one soundscape as its differences from NEUTRAL_SOUNDSCAPE --
 * every roster channel off at its defaults, the default environment -- so a
 * file names only what the soundscape actually sets:
 *
 *   1: { ...NEUTRAL_SOUNDSCAPE, name: 'Night rain', channels: {"rain-1":{"enabled":true,...}}, space: {...} },
 *
 * Reading goes through sanitizeAmbientSettings like any stored soundscape,
 * so a file from an older or newer build loads what this one understands
 * and nothing else. Soundscapes have no light and dark modes, so an id is
 * only the soundscape's position in the file.
 */
import {
  AMBIENT_CHANNEL_ROSTER,
  DEFAULT_AMBIENT_SPACE,
  DEFAULT_AMBIENT_WEATHER,
  MAX_AMBIENT_CUSTOM_PRESETS,
  ambientSettingsSignature,
  cloneSettings,
  createAmbientChannel,
  sanitizeAmbientSettings,
  type AmbientPreferences,
  type AmbientPreset,
  type AmbientSettings,
} from './ambientSound';
import { buildObjectDiff, formatPresetLine, formatPresetScalar, parsePresetLines } from './presetFile';

export const SOUNDSCAPE_FILE_EXTENSION = 'tds';
const BASE_TOKEN = 'NEUTRAL_SOUNDSCAPE';
const NAME_MAX_LENGTH = 40;

/** The soundscape every line is written against. */
export function neutralSoundscape(): AmbientSettings {
  return {
    channels: AMBIENT_CHANNEL_ROSTER.map((entry) => createAmbientChannel(entry.id, entry.kind, { enabled: false })),
    space: { ...DEFAULT_AMBIENT_SPACE },
    weather: { ...DEFAULT_AMBIENT_WEATHER },
  };
}

/** A name as a line can carry it: the format's strings have no escapes, so quotes are dropped. */
function fileSafeName(name: string): string {
  return name.replace(/['"]/g, '').trim().slice(0, NAME_MAX_LENGTH);
}

function channelsById(settings: AmbientSettings): Record<string, unknown> {
  // Solo is a listening aid, not part of the soundscape.
  return Object.fromEntries(settings.channels.map(({ id, solo: _solo, ...rest }) => [id, rest]));
}

/** The override fragments of one soundscape's line. */
function soundscapeParts(preset: AmbientPreset): string[] {
  const base = neutralSoundscape();
  const parts = [`name: ${formatPresetScalar(fileSafeName(preset.name))}`];
  const channels = buildObjectDiff(channelsById(preset.settings), channelsById(base));
  if (channels !== undefined) parts.push(`channels: ${JSON.stringify(channels)}`);
  const space = buildObjectDiff(preset.settings.space, base.space);
  if (space !== undefined) parts.push(`space: ${JSON.stringify(space)}`);
  const weather = buildObjectDiff(preset.settings.weather, base.weather);
  if (weather !== undefined) parts.push(`weather: ${JSON.stringify(weather)}`);
  return parts;
}

/** The text of a .tds file holding `presets`, in order. */
export function buildSoundscapeFile(presets: readonly AmbientPreset[]): string {
  return [
    '// Thockdown Soundscape file',
    '// Generated by Thockdown Notes',
    '//',
    `// Each line: <n>: { ...${BASE_TOKEN}, <overrides> },`,
    `// ${BASE_TOKEN} is every channel off at its defaults and the default environment.`,
    '',
    ...presets.map((preset, index) => formatPresetLine(index + 1, BASE_TOKEN, soundscapeParts(preset))),
  ].join('\n');
}

/**
 * The soundscapes a .tds file holds, each merged onto NEUTRAL_SOUNDSCAPE and
 * sanitized. Lines that are not soundscape lines are ignored; a file with
 * none reads as no soundscapes.
 */
export function parseSoundscapeFile(content: string): Array<{ name: string; settings: AmbientSettings }> {
  return parsePresetLines(content, BASE_TOKEN).map(({ id, overrides }) => {
    const base = neutralSoundscape();
    const channels = overrides.channels && typeof overrides.channels === 'object' ? overrides.channels as Record<string, Record<string, unknown>> : {};
    const settings = sanitizeAmbientSettings({
      channels: base.channels.map((channel) => ({ ...channel, ...(channels[channel.id] ?? {}) })),
      space: { ...base.space, ...(typeof overrides.space === 'object' ? overrides.space as object : {}) },
      weather: { ...base.weather, ...(typeof overrides.weather === 'object' ? overrides.weather as object : {}) },
    });
    const name = typeof overrides.name === 'string' && overrides.name.trim() ? fileSafeName(overrides.name) : `Soundscape ${id}`;
    return { name, settings: { ...settings, channels: settings.channels.map((channel) => ({ ...channel, solo: false })) } };
  });
}

/**
 * Preferences with the imported soundscapes added as custom ones: each that
 * does not already sound like a custom soundscape (by signature), in file
 * order, until MAX_AMBIENT_CUSTOM_PRESETS are held. Nothing else changes --
 * the active soundscape stays active. `makeId` gives each a fresh id.
 */
export function mergeImportedSoundscapes(
  preferences: AmbientPreferences,
  imported: ReadonlyArray<{ name: string; settings: AmbientSettings }>,
  makeId: () => string,
): AmbientPreferences {
  const signatures = new Set(preferences.customPresets.map((preset) => ambientSettingsSignature(preset.settings)));
  const customPresets = [...preferences.customPresets];
  for (const soundscape of imported) {
    if (customPresets.length >= MAX_AMBIENT_CUSTOM_PRESETS) break;
    const signature = ambientSettingsSignature(soundscape.settings);
    if (signatures.has(signature)) continue;
    signatures.add(signature);
    customPresets.push({ id: makeId(), name: soundscape.name, settings: cloneSettings(soundscape.settings) });
  }
  return { ...preferences, customPresets };
}

/** A fresh custom soundscape id, as a saved one gets. */
export function newSoundscapeId(): string {
  return `ambient-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
}

/**
 * The main process's half: a save and an open dialog for .tds files, and
 * nothing else -- the soundscapes themselves live in the renderer's state,
 * so building and reading a file happens there (unlike layouts, whose rows
 * live in the database the main process owns).
 */
export const SOUNDSCAPE_FILE_CHANNELS = {
  save: 'soundscape:saveFile',
  open: 'soundscape:openFile',
} as const;

export interface SoundscapeFileApi {
  /** Ask where to save and write `content` there; resolves when written or cancelled. */
  save(content: string, defaultName: string): Promise<void>;
  /** Ask for a .tds file and resolve to its text, or null when cancelled. */
  open(): Promise<string | null>;
}
