// CSS custom property names whose values get their alpha channel scaled by
// the "Border alpha" / "Box shadow alpha" sliders in Borders & Spacing.
// Every border-color and box-shadow token defined in styles/tokens.css
// (including their `-flip` counterparts, since `.shadow-flip` re-points the
// base token at its flip variant rather than duplicating it) must be listed
// here or it won't respond to the sliders.

export const BORDER_ALPHA_TOKENS: readonly string[] = [
  '--color-panel-border',
  '--color-border-dark-10',
  '--color-border-dark-20',
  '--color-border-dark-30',
  '--color-border-dark-40',
  '--color-border-dark-50',
  '--color-border-dark-60',
  '--color-border-dark-70',
  '--color-border-dark-80',
  '--color-border-dark-90',
  '--color-border-light-10',
  '--color-border-light-20',
  '--color-border-light-30',
  '--color-border-light-40',
  '--color-border-light-50',
  '--color-border-light-60',
  '--color-border-light-70',
  '--color-border-light-80',
  '--color-border-light-90',
  '--color-border-dark-10-flip',
  '--color-border-dark-20-flip',
  '--color-border-dark-30-flip',
  '--color-border-dark-40-flip',
  '--color-border-dark-50-flip',
  '--color-border-dark-60-flip',
  '--color-border-dark-70-flip',
  '--color-border-dark-80-flip',
  '--color-border-dark-90-flip',
  '--color-border-light-10-flip',
  '--color-border-light-20-flip',
  '--color-border-light-30-flip',
  '--color-border-light-40-flip',
  '--color-border-light-50-flip',
  '--color-border-light-60-flip',
  '--color-border-light-70-flip',
  '--color-border-light-80-flip',
  '--color-border-light-90-flip',
  '--color-tag-active-border',
  '--color-tag-suggested-border',
  '--color-danger-border',
  '--color-archive-border',
  '--color-border-blockquote',
  '--color-border-hr',
  '--btn-border-default',
  '--btn-border-hover',
  '--canonical-scroll-track-border',
  '--canonical-handle-border',
]

export const BOX_SHADOW_ALPHA_TOKENS: readonly string[] = [
  '--box-shadow-regular-light',
  '--box-shadow-inverted-light',
  '--box-shadow-regular',
  '--box-shadow-inverted',
  '--box-shadow-regular-harsh',
  '--box-shadow-inverted-harsh',
  '--box-shadow-regular-filtered',
  '--box-shadow-inverted-filtered',
  '--box-shadow-active-editor',
  '--box-shadow-regular-light-flip',
  '--box-shadow-inverted-light-flip',
  '--box-shadow-regular-flip',
  '--box-shadow-inverted-flip',
  '--box-shadow-regular-harsh-flip',
  '--box-shadow-inverted-harsh-flip',
  '--box-shadow-regular-filtered-flip',
  '--box-shadow-inverted-filtered-flip',
  '--box-shadow-active-editor-flip',
  '--btn-shadow-active',
  '--canonical-handle-shadow',
]
