export type HighlightColorKey =
  | 'caret'
  | 'search'
  | 'selectionEdit'
  | 'selectionRender'
  | 'textBase'
  | 'textEmbossEdit'
  | 'textEmbossRender'
  | 'textEmbossUi'
  | 'background'
  | 'topBackground'
  | 'bottomBackground'
  | 'gridOutline'
  | 'grid'
  | 'gutterBackground'
  | 'reviewLine'
  | 'warningLine'
  | 'lineNumber'
  | 'base'
  | 'inputFields'
  | 'appButtons'
  | 'markdownHeadline'
  | 'markdownList'
  | 'markdownBlockquote'
  | 'markdownCode'
  | 'markdownChecked'
  | 'markdownUnchecked'

export type HighlightColors = Record<HighlightColorKey, string>
