package com.thockdown.soundscapes;

import android.Manifest;
import android.content.Intent;
import android.os.Build;
import androidx.core.content.ContextCompat;
import com.getcapacitor.Plugin;
import com.getcapacitor.PluginCall;
import com.getcapacitor.PluginMethod;
import com.getcapacitor.annotation.CapacitorPlugin;
import com.getcapacitor.annotation.Permission;

/**
 * The Android side of mobile/src/backgroundAudioHost.ts.
 *
 * The soundscape itself is generated by Web Audio inside the WebView; this
 * plugin produces no sound. What it does is hold a foreground service of type
 * mediaPlayback open for as long as the web side says a soundscape is
 * audible, which is what keeps Android from freezing or killing the process
 * (and the WebView's audio thread with it) once the app is in the background
 * or the screen is off.
 *
 * The web side is the only authority on whether a soundscape is playing: it
 * calls start() and stop() from the same effect that drives the engine. The
 * notification's stop control is reported back as a "stopRequested" event,
 * which the web side handles like any other control.
 */
@CapacitorPlugin(
    name = "BackgroundAudio",
    permissions = { @Permission(alias = "notifications", strings = { Manifest.permission.POST_NOTIFICATIONS }) }
)
public class BackgroundAudioPlugin extends Plugin {
    /** The live plugin instance, for the service to report its stop control to. Null while no bridge is up. */
    private static BackgroundAudioPlugin instance;

    @Override
    public void load() {
        instance = this;
    }

    @Override
    protected void handleOnDestroy() {
        if (instance == this) instance = null;
    }

    @PluginMethod
    public void start(PluginCall call) {
        String title = call.getString("title", "Soundscape");
        Intent intent = new Intent(getContext(), SoundscapePlaybackService.class)
            .setAction(SoundscapePlaybackService.ACTION_START)
            .putExtra(SoundscapePlaybackService.EXTRA_TITLE, title);
        ContextCompat.startForegroundService(getContext(), intent);
        // Android 13+ shows a foreground service's notification only with
        // this permission. The service runs either way, so playback does not
        // wait on the answer; asking once is enough, and a refusal only hides
        // the notification and its stop control.
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU
            && getPermissionState("notifications") == com.getcapacitor.PermissionState.PROMPT) {
            requestPermissionForAlias("notifications", call, "afterNotificationPermission");
            return;
        }
        call.resolve();
    }

    @com.getcapacitor.annotation.PermissionCallback
    private void afterNotificationPermission(PluginCall call) {
        call.resolve();
    }

    @PluginMethod
    public void stop(PluginCall call) {
        getContext().stopService(new Intent(getContext(), SoundscapePlaybackService.class));
        call.resolve();
    }

    /** Called by the service when the listener presses its stop control. */
    static void reportStopRequested() {
        BackgroundAudioPlugin plugin = instance;
        if (plugin != null) plugin.notifyListeners("stopRequested", null);
    }
}
