import { describe, expect, it } from 'vitest'
import {
  fitPreviewHeightModel,
  planPreviewHeightSample,
  predictPreviewBlockHeight,
  predictPreviewBlockLines,
  resolvePreviewBlockShape,
} from './previewHeightModel'
import type { PreviewBlockShape, PreviewHeightSample } from './previewHeightModel'

const repeat = (chars: number) => 'x'.repeat(chars)

describe('resolvePreviewBlockShape', () => {
  it('reads the shape off the first line\'s sigil', () => {
    expect(resolvePreviewBlockShape('# Title')).toBe('heading1')
    expect(resolvePreviewBlockShape('## Section')).toBe('heading2')
    expect(resolvePreviewBlockShape('#### Deep')).toBe('heading3plus')
    expect(resolvePreviewBlockShape('> quoted')).toBe('quote')
    expect(resolvePreviewBlockShape('- item\n- item')).toBe('list')
    expect(resolvePreviewBlockShape('3. item')).toBe('list')
    expect(resolvePreviewBlockShape('```js\ncode()\n```')).toBe('code')
    expect(resolvePreviewBlockShape('| a | b |\n| - | - |')).toBe('table')
    expect(resolvePreviewBlockShape('![alt](img.png)')).toBe('media')
    expect(resolvePreviewBlockShape('---')).toBe('rule')
    expect(resolvePreviewBlockShape('Just prose.')).toBe('paragraph')
  })

  it('does not mistake a hyphenated sentence for a list or a rule', () => {
    expect(resolvePreviewBlockShape('-and then he left')).toBe('paragraph')
    expect(resolvePreviewBlockShape('--')).toBe('paragraph')
  })
})

describe('predictPreviewBlockLines', () => {
  it('counts wrapped lines per source line, not per block', () => {
    // Five short list items are five lines; summing the block's characters
    // would call the whole thing one line.
    expect(predictPreviewBlockLines('- one\n- two\n- three\n- four\n- five', 80)).toBe(5)
  })

  it('wraps a long line by the characters that will actually render', () => {
    // 240 visible characters at 80/line is 3 lines; the "> " prefix is
    // markup, not rendered text.
    expect(predictPreviewBlockLines(`> ${repeat(240)}`, 80)).toBe(3)
  })

  it('gives an empty line inside a block its line box', () => {
    expect(predictPreviewBlockLines('```\n\n```', 80)).toBe(3)
  })

  it('never returns less than one line', () => {
    expect(predictPreviewBlockLines('', 80)).toBe(1)
    expect(predictPreviewBlockLines('x', 0)).toBe(1)
  })
})

describe('fitPreviewHeightModel', () => {
  /** A document whose real heights follow a known law, per shape. */
  const syntheticSample = (text: string): PreviewHeightSample => {
    const shape = resolvePreviewBlockShape(text)
    const law: Partial<Record<PreviewBlockShape, { intercept: number; perLine: number; cpl: number }>> = {
      paragraph: { intercept: 16, perLine: 24, cpl: 72 },
      heading2: { intercept: 40, perLine: 36, cpl: 40 },
      list: { intercept: 12, perLine: 22, cpl: 68 },
    }
    const { intercept, perLine, cpl } = law[shape] ?? law.paragraph!
    return { text, heightPx: intercept + (perLine * predictPreviewBlockLines(text, cpl)) }
  }

  const syntheticDocument = () => {
    const texts: string[] = []
    for (let i = 0; i < 40; i += 1) {
      texts.push(repeat(20 + ((i * 37) % 400)))
      if (i % 5 === 0) texts.push(`## ${repeat(10 + ((i * 13) % 90))}`)
      if (i % 4 === 0) texts.push(`- ${repeat(15 + ((i * 7) % 60))}\n- ${repeat(30)}`)
    }
    return texts
  }

  it('recovers the law it was sampled from, per shape', () => {
    const texts = syntheticDocument()
    const model = fitPreviewHeightModel(texts.map(syntheticSample))!

    expect(model).not.toBeNull()
    // A model fitted from data generated by exactly this functional form
    // should reproduce it almost exactly; anything above a percent or two
    // means the search or the solve is wrong, not that the data is noisy.
    expect(model.medianErrorPct).toBeLessThan(1)
    expect(Math.abs(model.biasPct)).toBeLessThan(1)

    for (const text of texts) {
      const truth = syntheticSample(text).heightPx
      expect(Math.abs(predictPreviewBlockHeight(model, text) - truth)).toBeLessThan(truth * 0.05)
    }
  })

  it('predicts the document total far better than a flat estimate', () => {
    const texts = syntheticDocument()
    const truth = texts.reduce((sum, text) => sum + syntheticSample(text).heightPx, 0)
    // Fit from a *sample*, then predict the whole document -- the real use.
    const sampleIndices = planPreviewHeightSample({
      blockCount: texts.length,
      shapeAt: (index) => resolvePreviewBlockShape(texts[index]),
      perShape: 12,
      maxTotal: 60,
    })
    const model = fitPreviewHeightModel(sampleIndices.map((index) => syntheticSample(texts[index])))!

    const predicted = texts.reduce((sum, text) => sum + predictPreviewBlockHeight(model, text), 0)
    const flat = texts.length * 56

    expect(Math.abs(predicted - truth) / truth).toBeLessThan(0.02)
    expect(Math.abs(predicted - truth)).toBeLessThan(Math.abs(flat - truth) / 10)
  })

  it('reports a large error when height is not a function of the text', () => {
    // Images: same source length, wildly different rendered heights. The
    // caller uses this number to decide NOT to trust the model.
    const samples = Array.from({ length: 20 }, (_, i) => ({
      text: `![alt](image-${i}.png)`,
      heightPx: 40 + ((i * 137) % 700),
    }))
    expect(fitPreviewHeightModel(samples)!.medianErrorPct).toBeGreaterThan(20)
  })

  it('falls back to the pooled fit for a shape with too few samples', () => {
    const samples = [
      ...Array.from({ length: 12 }, (_, i) => syntheticSample(repeat(40 + (i * 20)))),
      syntheticSample('| a | b |'),
    ]
    const model = fitPreviewHeightModel(samples)!
    expect(model.shapes.table).toBeUndefined()
    expect(predictPreviewBlockHeight(model, '| a | b |')).toBeGreaterThan(0)
  })

  it('returns null when there is nothing measurable to fit', () => {
    expect(fitPreviewHeightModel([])).toBeNull()
    expect(fitPreviewHeightModel([{ text: 'x', heightPx: 0 }])).toBeNull()
  })
})

describe('planPreviewHeightSample', () => {
  const shapes: PreviewBlockShape[] = ['paragraph', 'heading2', 'list', 'quote']
  const shapeAt = (index: number) => shapes[index % shapes.length]

  it('always includes block 0, which has a margin the rest do not', () => {
    expect(planPreviewHeightSample({ blockCount: 500, shapeAt, perShape: 4, maxTotal: 40 })).toContain(0)
  })

  it('covers every shape present, not just the common one', () => {
    const picked = planPreviewHeightSample({ blockCount: 500, shapeAt, perShape: 4, maxTotal: 40 })
    expect(new Set(picked.map(shapeAt)).size).toBe(shapes.length)
  })

  it('spreads through the document rather than taking the first N', () => {
    const picked = planPreviewHeightSample({ blockCount: 1000, shapeAt, perShape: 6, maxTotal: 40 })
    expect(Math.max(...picked)).toBeGreaterThan(900)
  })

  it('stays inside its budget and returns each index once, in order', () => {
    const picked = planPreviewHeightSample({ blockCount: 5000, shapeAt, perShape: 30, maxTotal: 24 })
    expect(picked.length).toBeLessThanOrEqual(24)
    expect(new Set(picked).size).toBe(picked.length)
    expect([...picked].sort((a, b) => a - b)).toEqual(picked)
  })

  it('handles a document smaller than the sample budget', () => {
    expect(planPreviewHeightSample({ blockCount: 3, shapeAt, perShape: 10, maxTotal: 40 })).toEqual([0, 1, 2])
    expect(planPreviewHeightSample({ blockCount: 0, shapeAt, perShape: 10, maxTotal: 40 })).toEqual([])
  })
})

describe('planPreviewHeightSample budget allocation', () => {
  // 90% paragraphs, 10% headings -- the shape mix of an ordinary document.
  const shapeAt = (index: number): PreviewBlockShape => (index % 10 === 0 ? 'heading2' : 'paragraph')

  it('spends most of the budget on the shape most of the document is', () => {
    const picked = planPreviewHeightSample({ blockCount: 5000, shapeAt, perShape: 6, maxTotal: 160 })
    const paragraphs = picked.filter((index) => shapeAt(index) === 'paragraph').length
    const headings = picked.filter((index) => shapeAt(index) === 'heading2').length
    expect(paragraphs).toBeGreaterThan(headings * 3)
    // ...but never at the cost of leaving the rare shape unfittable.
    expect(headings).toBeGreaterThanOrEqual(6)
  })

  it('still respects the ceiling once shares are handed out', () => {
    const picked = planPreviewHeightSample({ blockCount: 5000, shapeAt, perShape: 6, maxTotal: 40 })
    expect(picked.length).toBeLessThanOrEqual(40)
  })
})
