// The save model, and the one function that changes it.
//
// Shaped as TABLES even though it is currently written as a single JSON
// document through the app-state path: `profile` is a row, `games` are
// rows, `holdings` and `outcomes` are rows referring to a game by id. That
// is not ceremony -- it is so that moving this into the app's SQLite
// database (electron/databaseService.ts) is an insert loop per array rather
// than a redesign. The one deliberate exception is the director's stack,
// which holds opaque stage state by design and is therefore a blob wherever
// it lives.
//
// TWO STORES, and the boundary is absolute:
//   - CONTENT (../content) ships with the app, is never written, and
//     changes every release.
//   - SAVE (here) belongs to the player and is migrated.
// Save refers to content BY ID and tolerates an id content no longer has --
// dropped, never crashed on. That is what lets a monster or a trinket be
// deleted without breaking somebody's game.
//
// WHY THE DIRECTOR'S STACK IS NOT ON THE GAME ROW: the welcome screen runs
// before any game exists and after one ends, so the stack outlives every
// individual game. It sits beside `activeGameId`, which says what the
// current stack is playing. A second game slot is a matter of suspending a
// stack into its row, and nothing here forecloses it -- but the field for
// it is not written until something uses it.

import { armorFromHoldings, applyAcquisition, NO_ARMOR, type Armor } from './armor'
import { resolveProfile, type EffectiveProfile, type HoldingCounts, type Modifier, type ModifierKind } from './modifiers'
import { clampBaseStats, createStatBlock, deriveStats, type StatBlock } from './stats'
import type { Effect } from './effects'
import { FIRST_MILESTONE_THRESHOLD, takeMilestone } from './milestones'
import { canAllocateStatPoint } from './motes'
import type { JsonObject } from '../core/json'
import { createSeed, type RngState } from '../core/rng'
import { DEFAULT_DIFFICULTY, type Difficulty } from './difficulty'

/**
 * Bumped when the SHAPE below changes incompatibly, which DISCARDS the save
 * (save.ts returns null for any other version) rather than migrating it.
 *
 * 2: experience split into `experienceEarned` / `experienceSpentOnTraits`
 * with a stored `experienceToNextStatPoint`. A v1 save has one running
 * balance, and there is no honest way to read a total out of it -- whatever
 * was spent is simply gone from the number. Guessing would put a run at the
 * wrong distance from its next stat point with nothing to say so.
 *
 * 3: gold split the same way (`goldEarned` / `goldSpentOnItems`) now that it
 * drives a ladder of its own, and fame became that ladder's points
 * (`famePoints` / `famePointsSpent` / `goldToNextFamePoint`) rather than a
 * bare score. `statPointsAcquired` was renamed `statPointsSpent`, which is
 * what it always counted -- it is incremented by the allocation, not by the
 * attainment, and the old name had already cost one wrapper function written
 * purely to hide it. A v2 save's `goldUnits` is a balance with the same
 * unrecoverable total as v1's motes.
 */
export const SAVE_VERSION = 3

/** One frame of the director's stack: which stage, and its own private state. */
export interface StageFrame {
  stageId: string
  state: JsonObject
}

/**
 * Where the player is, independent of which game they are in. Persisted in
 * full, which is the whole of "leave at any moment and come back to the
 * same screen" -- including halfway through a fight or a nested menu.
 */
export interface DirectorState {
  stack: StageFrame[]
  /**
   * What the chapter bar is showing, NEWEST FIRST. Narration belongs to the
   * TRANSITION, not to the screen: it is the result of the previous choice
   * and the frame for the next one, so it is carried here rather than
   * regenerated by whichever stage happens to be current.
   *
   * A LIST because a stage may have a sequence to show rather than a line --
   * see core/stage.ts. The director stores whatever the last transition
   * handed it and never adds to it: a stage that accumulates keeps its own
   * entries in its own state, so leaving mid-round and coming back finds the
   * round's story where the round itself is.
   */
  narration: string[]
  rng: RngState
}

/** Permanent, across every game ever played. One row. */
export interface Profile {
  gamesStarted: number
  gamesEnded: number
  bestFame: number
}

export const EMPTY_PROFILE: Profile = { gamesStarted: 0, gamesEnded: 0, bestFame: 0 }

/** One game slot. Multiple are possible by construction; only one is offered today. */
export interface GameRecord {
  id: string
  /** Where this game's randomness began. With the choices made, it replays the game. */
  seed: RngState
  createdAtMs: number
  updatedAtMs: number
  status: 'active' | 'over'
  endedReason?: 'defeat' | 'retired'
  /** 1-based. */
  level: number
  /**
   * FIXED when the run starts, from the settings as they stood then. A
   * preset changed mid-run would rewrite what every fight already fought was
   * worth, so the settings hold the choice for the NEXT run and the record
   * holds the one this run is being played under.
   */
  difficulty: Difficulty
  /**
   * The thumb on the scale, 0..1, fixed when the run starts for the same
   * reason the preset is. See model/chance.ts's `pressThumb`.
   */
  successAdjust: number
  regionId: string | null
  baseStats: StatBlock
  /** Points earned and not yet spent on a stat. */
  /** Points ever spent on a stat -- what pushes the next threshold away. */
  statPointsSpent: number
  /**
   * Every mote this run has ever earned. MONOTONIC: spending never reduces
   * it, because it is the milestone track as well as the source of the
   * currency. See model/motes.ts for why the two are stored apart.
   */
  experienceEarned: number
  /** Of those, how many have gone on traits. The balance is the difference. */
  experienceSpentOnTraits: number
  /** What `experienceEarned` must reach for the next stat point. Starts at 10. */
  experienceToNextStatPoint: number
  /**
   * Every gold piece this run has ever earned. MONOTONIC, for the same
   * reason `experienceEarned` is: it is the fame ladder's position as well
   * as the source of the currency. See model/gold.ts.
   */
  goldEarned: number
  /** Of those, how many have gone on items. The balance is the difference. */
  goldSpentOnItems: number
  /** What `goldEarned` must reach for the next fame point. Starts at 10. */
  goldToNextFamePoint: number
  /**
   * Fame points earned and not yet spent. This is the run's SCORE: fame is
   * the ladder gold feeds, on the same numbers stat points sit on, so a
   * fame point is a milestone reached rather than a running total of gold.
   */
  famePoints: number
  /** Points ever spent -- what pushes the next fame threshold away. */
  famePointsSpent: number
  hitPoints: number
  armor: Armor
}

export interface HoldingRow {
  gameId: string
  kind: ModifierKind
  modifierId: string
  /** Order of acquisition, so "keep one" can show them as they were found. */
  seq: number
}

export interface OutcomeRow {
  gameId: string
  seq: number
  /** Content introduces new kinds; the schema never changes for them. */
  outcome: string
  payload: JsonObject
}

/**
 * What the player has chosen for the game itself, rather than for any one
 * run. Persisted across runs, and copied onto a run when it starts.
 */
export interface GameSettings {
  difficulty: Difficulty
  /**
   * A TUNING parameter rather than a player-facing one: it scales a player's
   * chance to FAIL and a monster's chance to SUCCEED (model/chance.ts's
   * `pressThumb`), which puts a thumb on the scale while leaving both sides
   * reading the same stat table. 0 changes nothing.
   *
   * Nothing in the game sets it -- there is no screen for it, on purpose.
   * The simulation harness does (`npm run adventure:sim -- --success-adjust`),
   * which is what it is for while the shape of a run is still being found.
   */
  successAdjust: number
}

export const DEFAULT_SETTINGS: GameSettings = { difficulty: DEFAULT_DIFFICULTY, successAdjust: 0 }

export interface GameSave {
  version: number
  profile: Profile
  settings: GameSettings
  games: GameRecord[]
  holdings: HoldingRow[]
  outcomes: OutcomeRow[]
  activeGameId: string | null
  director: DirectorState
}

export function emptySave(rng: RngState): GameSave {
  return {
    version: SAVE_VERSION,
    profile: EMPTY_PROFILE,
    settings: DEFAULT_SETTINGS,
    games: [],
    holdings: [],
    outcomes: [],
    activeGameId: null,
    director: { stack: [], narration: [], rng },
  }
}

/**
 * Sets the tuning thumb (model/chance.ts) on the settings AND on the run in
 * progress, and it is the one thing in the game that deliberately reaches
 * into a run that has already started.
 *
 * The difficulty preset is frozen at a run's start because changing it would
 * rewrite what every fight already fought was worth -- a promise to a PLAYER.
 * The thumb is an instrument: the whole use of a debugging slider is to move
 * it and feel the difference in the fight that is on screen, and one that
 * only took effect on the next run would be answering a question nobody
 * asked. The two behave differently on purpose.
 *
 * Not an `Effect`, and that is not an oversight: the effect vocabulary is
 * what a STAGE may ask the world to change (model/effects.ts), and this is
 * the host's own control rather than anything the game offers.
 */
export function withSuccessAdjust(save: GameSave, successAdjust: number): GameSave {
  // Rounded as well as clamped: a slider stepping by 0.05 arrives carrying
  // 0.6000000000000001, and that is what would be stored, read back and
  // eventually shown to somebody as a percentage.
  const thumb = Math.round(Math.max(0, Math.min(1, successAdjust)) * 100) / 100
  if (thumb === save.settings.successAdjust && activeGame(save)?.successAdjust === thumb) return save
  return {
    ...save,
    settings: { ...save.settings, successAdjust: thumb },
    games: save.games.map((game) => (game.id === save.activeGameId ? { ...game, successAdjust: thumb } : game)),
  }
}

export function activeGame(save: GameSave): GameRecord | null {
  return save.games.find((game) => game.id === save.activeGameId) ?? null
}

/** The most recent game that can still be played, for "continue". */
export function resumableGame(save: GameSave): GameRecord | null {
  return (
    [...save.games]
      .filter((game) => game.status === 'active')
      .sort((left, right) => right.updatedAtMs - left.updatedAtMs)[0] ?? null
  )
}

export function holdingsOf(save: GameSave, gameId: string): HoldingRow[] {
  return save.holdings.filter((row) => row.gameId === gameId).sort((left, right) => left.seq - right.seq)
}

/** Held modifiers, resolved against content. Ids content no longer has are dropped. */
export function heldModifiers(save: GameSave, gameId: string, catalog: ReadonlyMap<string, Modifier>): Modifier[] {
  return holdingsOf(save, gameId).flatMap((row) => {
    const modifier = catalog.get(row.modifierId)
    return modifier ? [modifier] : []
  })
}

export function holdingCounts(held: readonly Modifier[]): HoldingCounts {
  return {
    items: held.filter((modifier) => modifier.kind === 'item').length,
    traits: held.filter((modifier) => modifier.kind === 'trait').length,
  }
}

/** The player as every formula sees them. */
export function profileOf(save: GameSave, game: GameRecord, catalog: ReadonlyMap<string, Modifier>): EffectiveProfile {
  const held = heldModifiers(save, game.id, catalog)
  // The record's own hit points ride along, so a conditional effect ("harder
  // to kill with their back to the wall") is already in every number every
  // caller reads. The record is written after each blow, so this is current
  // inside a fight as well as outside one.
  return resolveProfile(game.baseStats, held, holdingCounts(held), { hitPoints: game.hitPoints })
}

function nextSeq(rows: readonly { gameId: string; seq: number }[], gameId: string): number {
  return rows.reduce((highest, row) => (row.gameId === gameId ? Math.max(highest, row.seq) : highest), 0) + 1
}

function createGame(id: string, seed: RngState, nowMs: number, settings: GameSettings): GameRecord {
  const baseStats = createStatBlock(0)
  return {
    id,
    seed,
    createdAtMs: nowMs,
    updatedAtMs: nowMs,
    status: 'active',
    level: 1,
    difficulty: settings.difficulty,
    successAdjust: settings.successAdjust,
    regionId: null,
    baseStats,
    statPointsSpent: 0,
    experienceEarned: 0,
    experienceSpentOnTraits: 0,
    experienceToNextStatPoint: FIRST_MILESTONE_THRESHOLD,
    goldEarned: 0,
    goldSpentOnItems: 0,
    goldToNextFamePoint: FIRST_MILESTONE_THRESHOLD,
    famePoints: 0,
    famePointsSpent: 0,
    hitPoints: deriveStats(clampBaseStats(baseStats)).maxHitPoints,
    armor: NO_ARMOR,
  }
}

/**
 * Applies ONE effect to the save. Every write passes through here, which is
 * what makes "modules never write" enforceable rather than merely stated: a
 * stage that wants to change something it has no effect for has to add one,
 * in public, rather than reach into state from wherever it happens to be.
 *
 * Effects that need a game act on the ACTIVE one and are no-ops without it,
 * rather than throwing: a stage asking to heal a player who no longer
 * exists is a bug to see in a test, not a crash in somebody's evening.
 */
export function applyEffect(
  save: GameSave,
  effect: Effect,
  catalog: ReadonlyMap<string, Modifier>,
  nowMs: number,
): GameSave {
  if (effect.kind === 'startGame') {
    // The seed is drawn HERE, from the clock, because this is the director
    // acting rather than a stage: a stage that could read a clock would
    // stop being a pure function of its inputs, and the game would stop
    // being replayable. See core/rng.ts.
    const seed = createSeed(nowMs)
    // The id is built from the CLOCK, so two games started in the same
    // millisecond were handed the same one -- the save then held two rows
    // with one id and `activeGame` returned the older, dead one, which is a
    // run that begins at zero hit points and ends on its first blow. Rare by
    // hand and instant in a test that passes a fixed clock. Disambiguated
    // against what the save already holds rather than made likelier to be
    // unique.
    let id = `game-${nowMs.toString(36)}-${seed.toString(36)}`
    for (let suffix = 2; save.games.some((existing) => existing.id === id); suffix += 1) {
      id = `game-${nowMs.toString(36)}-${seed.toString(36)}-${suffix}`
    }
    const game = createGame(id, seed, nowMs, save.settings)
    return {
      ...save,
      games: [...save.games, game],
      activeGameId: game.id,
      director: { ...save.director, rng: seed },
      profile: { ...save.profile, gamesStarted: save.profile.gamesStarted + 1 },
    }
  }

  if (effect.kind === 'setDifficulty') {
    // Settings, not the record: applies to runs that have not begun. A run in
    // progress keeps the preset it was started under.
    return { ...save, settings: { ...save.settings, difficulty: effect.difficulty } }
  }

  if (effect.kind === 'openGame') {
    return save.games.some((game) => game.id === effect.gameId) ? { ...save, activeGameId: effect.gameId } : save
  }

  if (effect.kind === 'closeGame') return { ...save, activeGameId: null }

  const game = activeGame(save)
  if (!game) return save
  const gameId = game.id

  const replace = (next: Partial<GameRecord>): GameSave => ({
    ...save,
    games: save.games.map((candidate) => (candidate.id === gameId ? { ...candidate, ...next } : candidate)),
  })

  switch (effect.kind) {
    case 'adjustBaseStat':
      return replace({
        baseStats: clampBaseStats({ ...game.baseStats, [effect.stat]: game.baseStats[effect.stat] + effect.amount }),
      })

    case 'acquireModifier': {
      const withHolding: GameSave = {
        ...save,
        holdings: [
          ...save.holdings,
          { gameId, kind: effect.modifierKind, modifierId: effect.modifierId, seq: nextSeq(save.holdings, gameId) },
        ],
      }
      const modifier = catalog.get(effect.modifierId)
      if (!modifier) return withHolding
      // On-acquire effects fire HERE and exactly once. See armor.ts.
      const armor = applyAcquisition(game.armor, modifier)
      return {
        ...withHolding,
        games: withHolding.games.map((candidate) => (candidate.id === gameId ? { ...candidate, armor } : candidate)),
      }
    }

    case 'releaseModifier':
      return {
        ...save,
        holdings: save.holdings.filter(
          (row) => !(row.gameId === gameId && row.kind === effect.modifierKind && row.modifierId === effect.modifierId),
        ),
      }

    case 'adjustHitPoints': {
      const max = profileOf(save, game, catalog).derived.maxHitPoints
      return replace({ hitPoints: Math.max(0, Math.min(max, game.hitPoints + effect.amount)) })
    }

    case 'setArmor':
      return replace({ armor: { fromItems: effect.fromItems, natural: effect.natural } })

    case 'grantExperience':
      // Earning only ever adds. Spending is `spendExperience`, and it is a
      // different field on purpose -- see model/motes.ts.
      return replace({ experienceEarned: Math.max(0, game.experienceEarned + effect.units) })

    case 'spendExperience':
      return replace({
        experienceSpentOnTraits: Math.max(0, game.experienceSpentOnTraits + effect.units),
      })

    case 'allocateStatPoint': {
      // Gated on the LADDER, which is the only representation of "a point is
      // waiting" there is now. It used to be gated on a stored counter that
      // nothing incremented, so this effect could never do anything at all.
      if (!canAllocateStatPoint(game.experienceEarned, game.experienceToNextStatPoint)) return save
      const taken = takeMilestone(game.experienceToNextStatPoint, game.statPointsSpent)
      return replace({
        statPointsSpent: taken.pointsSpent,
        experienceToNextStatPoint: taken.threshold,
      })
    }

    case 'grantGold':
      // Earning only ever adds, exactly as with experience: the total is the
      // fame ladder's position. Spending is `spendGold`.
      return replace({ goldEarned: Math.max(0, game.goldEarned + effect.units) })

    case 'spendGold':
      return replace({ goldSpentOnItems: Math.max(0, game.goldSpentOnItems + effect.units) })

    case 'grantFamePoints':
      return replace({ famePoints: Math.max(0, game.famePoints + effect.amount) })

    case 'allocateFamePoint': {
      // The mirror of allocateStatPoint, on the same ladder. What a fame
      // point BUYS is not written yet -- this only moves the ladder, which
      // is the half that is settled.
      if (game.famePoints <= 0) return save
      const taken = takeMilestone(game.goldToNextFamePoint, game.famePointsSpent)
      return replace({
        famePoints: game.famePoints - 1,
        famePointsSpent: taken.pointsSpent,
        goldToNextFamePoint: taken.threshold,
      })
    }

    case 'setRegion':
      return replace({ regionId: effect.regionId })

    case 'advanceLevel': {
      // A new level restores hit points and REBUILDS armor from what is
      // held -- an item carried over counts as a fresh acquisition, which
      // is the rule that makes carrying an armour item a real choice.
      const held = heldModifiers(save, gameId, catalog)
      const max = resolveProfile(game.baseStats, held, holdingCounts(held)).derived.maxHitPoints
      return replace({ level: game.level + 1, hitPoints: max, armor: armorFromHoldings(held) })
    }

    case 'endGame': {
      const ended = replace({ status: 'over', endedReason: effect.reason })
      return {
        ...ended,
        profile: {
          ...ended.profile,
          gamesEnded: ended.profile.gamesEnded + 1,
          // Everything the run ever ATTAINED, not what is left in hand: a
          // player who spent their fame points did not score less for it.
          bestFame: Math.max(ended.profile.bestFame, game.famePoints + game.famePointsSpent),
        },
      }
    }

    case 'recordOutcome':
      return {
        ...save,
        outcomes: [
          ...save.outcomes,
          { gameId, seq: nextSeq(save.outcomes, gameId), outcome: effect.outcome, payload: effect.payload ?? {} },
        ],
      }
  }
}

/**
 * HIT POINTS FOLLOW THEIR CEILING, in both directions, after every single
 * effect.
 *
 * This is NOT healing, and the rule says why (docs/adventure-game-design.md):
 * current and maximum move TOGETHER, so nothing that was lost is restored and
 * the equation stays readable. Raising the maximum on its own would be
 * *taking damage* equal to the delta -- which is the real reason the grant is
 * not optional, over and above "+25 hit points" otherwise being a number on
 * the tab bar that changed nothing.
 *
 * A fall is the same rule from the other end: dropping the item that granted
 * the ceiling cannot leave a character standing above their own maximum. Its
 * one planned moment is the end of a level, where items and traits are given
 * up -- and there the ORDER matters: restore hit points first, then remove
 * them, so the fall lands on a full pool rather than driving a depleted one
 * to nothing.
 *
 * Applied here, once, around every effect, rather than in the two or three
 * branches that happen to change a maximum today -- a rule stated once has to
 * hold everywhere it applies, and the next effect that moves the ceiling will
 * not know to ask.
 */
function followMaxHitPoints(before: GameSave, after: GameSave, catalog: ReadonlyMap<string, Modifier>): GameSave {
  const previous = activeGame(before)
  const current = activeGame(after)
  if (!current) return after
  // A run that has only just started has no hit points to follow: character
  // creation fills them at the end, on purpose (see that stage).
  if (!previous || previous.id !== current.id) return after

  const wasMax = profileOf(before, previous, catalog).derived.maxHitPoints
  const nowMax = profileOf(after, current, catalog).derived.maxHitPoints
  const gained = Math.max(0, nowMax - wasMax)
  const hitPoints = Math.max(0, Math.min(nowMax, current.hitPoints + gained))
  if (hitPoints === current.hitPoints) return after
  return {
    ...after,
    games: after.games.map((game) => (game.id === current.id ? { ...game, hitPoints } : game)),
  }
}

export function applyEffects(
  save: GameSave,
  effects: readonly Effect[],
  catalog: ReadonlyMap<string, Modifier>,
  nowMs: number,
): GameSave {
  const next = effects.reduce(
    (current, effect) => followMaxHitPoints(current, applyEffect(current, effect, catalog, nowMs), catalog),
    save,
  )
  if (!next.activeGameId) return next
  return {
    ...next,
    games: next.games.map((game) => (game.id === next.activeGameId ? { ...game, updatedAtMs: nowMs } : game)),
  }
}
