name: Build macOS DMG

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  build-mac:
    runs-on: macos-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Read version
        id: version
        run: echo "version=$(node -p \"require('./package.json').version\")" >> "$GITHUB_OUTPUT"

      - name: Set up Node modules
        run: npm ci

      - name: Build app
        run: npm run build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload DMG
        uses: actions/upload-artifact@v4
        with:
          name: Thockdown-Notes-mac-${{ steps.version.outputs.version }}-dmg
          path: release/**/**/*.dmg
